import { ProthesuDocHistory } from './protheus-doc-history';
import { ProthesuDocParam } from './protheus-doc-parm';
import { ProthesuDocReturn } from './protheus-doc-return';
export declare class ItemProtheusDoc {
    functionName: string | undefined;
    accessLevel: string | undefined;
    author: string | undefined;
    build: string | undefined;
    country: string | undefined;
    database: string | undefined;
    defvalue: string | undefined;
    description: string;
    deprecated: string | undefined;
    example: string[];
    history: ProthesuDocHistory[];
    sample: string | undefined;
    language: string | undefined;
    link: string[];
    obs: string | undefined;
    param: ProthesuDocParam[];
    proptype: string | undefined;
    protected: string | undefined;
    readonly: string | undefined;
    return: ProthesuDocReturn[];
    source: string | undefined;
    systemOper: string | undefined;
    see: string | undefined;
    since: string | undefined;
    table: string | undefined;
    todo: string | undefined;
    type: string | undefined;
    version: string | undefined;
}
